spring:  
 profiles:
    active:
    - dev1
---
spring: 
    profiles: dev1  #开发环境
    application:
        name: springcloud1-dev
---
spring: 
    profiles: test  #测试环境
    application:
        name: springcloud1-test
