spring:  
 profiles:
    active:
    - dev
---
spring: 
    profiles: dev  #开发环境
    application:
        name: springcloud1-dev
server:
    port: 8201

---
spring: 
    profiles: test  #测试环境
    application:
        name: springcloud1-test
    
server:
    port: 8202
